Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using mission9_ear69.Models;
namespace mission9_ear69.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket basket;
        public CartSummaryViewComponent(Basket basketS)
        {
            basket = basketS;
        }
        public IViewComponentResult Invoke()
        {
            return View(basket);
        }
    }
}

Components/TypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using mission9_ear69.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission9_ear69.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public TypesViewComponent(IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["bookCategory"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            return View(types);
        }
    }
}

Views/Shared/BookSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Book
@*book partial view*@
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Title
            <span class="badge badge-pill badge-primary bg-dark" style="float:right">
                <small>Price : @Model.Price.ToString("c")</small>
            </span>
        </h4>

        <div class="card-text p-1"> Book Author: @Model.Author</div>
        <div class="card-text p-1"> Book Publisher: @Model.Publisher</div>
        <div class="card-text p-1"> Book Isbn: @Model.Isbn</div>
        <div class="card-text p-1"> Book Classification: @Model.Classification</div>
        <div class="card-text p-1"> Book Category: @Model.Category</div>
        <div class="card-text p-1"> Book PageCount: @Model.PageCount</div>
        <div class="card-text p-1"> Book Price: @Model.Price</div>
        <form method="post" asp-page="/ShoppingCart">
            <span class="card-text">
                <input type="hidden" asp-for="@Model.BookId" />
                <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                <button type="submit" class="btn btn-info btn-sm float-end">Add to Cart</button>
               
            </span>

        </form>

    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">Eddies Bookstore</div>
                <div class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">Book Store</span>
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            <vc:types></vc:types>
        </div>
        <div class="col-9">


            @RenderBody()
        </div>
        <footer>Eddies Bookstore</footer>
        @*this is the code that allows the spinner in boostrap and the accordian*@
        <div class="spinner-border text-success" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
        <div class="accordion accordion-flush" id="accordionFlushExample">
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                        Accordion Item #1
                    </button>
                </h2>
                <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">Placeholder content for this accordion, which is intended to demonstrate the <code>.accordion-flush</code> class. This is the first item's accordion body.</div>
                </div>
            </div>
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingTwo">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                        Accordion Item #2
                    </button>
                </h2>
                <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">Placeholder content for this accordion, which is intended to demonstrate the <code>.accordion-flush</code> class. This is the second item's accordion body. Let's imagine this being filled with some actual content.</div>
                </div>
            </div>
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingThree">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                        Accordion Item #3
                    </button>
                </h2>
                <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">Placeholder content for this accordion, which is intended to demonstrate the <code>.accordion-flush</code> class. This is the third item's accordion body. Nothing more exciting happening here in terms of content, but just filling up the space to make it look, at least at first glance, a bit more representative of how this would look in a real-world application.</div>
                </div>
            </div>
        </div>
    </div>

    <script src="~/lib/twitter-bootstrap/js/bootstrap.js"></script>
</body>
</html>