Models/ShoppingCart.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace mission9_ear69.Models
{
    public class ShoppingCart
    {   [Key]
        [BindNever]
        public int ShoppingCartId { get; set; }

        [BindNever]
        public ICollection<BasketLineItem> Lines { get; set; }
        [Required(ErrorMessage ="Enter name:")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Enter address:")]
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }

        [Required(ErrorMessage = "Enter city:")]
        public string City { get; set; }
        [Required(ErrorMessage = "Enter State:")]
        public string State { get; set; }
        public string Zip { get; set; }
        [Required(ErrorMessage = "Enter country:")]
        public string Country { get; set; }

    }
}

Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using mission9_ear69.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission9_ear69.Controllers
{
    public class ShoppingCartController : Controller
    {
        private IShoppingCartRepository repo { get; set; }
        private Basket basket { get; set; }
        public ShoppingCartController(IShoppingCartRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }
        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new ShoppingCart());
        }

        [HttpPost]
        public IActionResult Checkout(ShoppingCart shoppingCart)
        {
            if (basket.Items.Count()==0)
            {
                ModelState.AddModelError("", "Sorry bruv your ting is empty");
            }
            if (ModelState.IsValid)
            {
                shoppingCart.Lines = basket.Items.ToArray();
                repo.SaveShoppingCart(shoppingCart);
                basket.ClearBasekt();

                return RedirectToPage("/Completed");
            }
            else
            {
                return View();
            }
        }
    }
}

Pages/Completed.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace mission9_ear69.Pages
{
    public class CompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/ShoppingCart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using mission9_ear69.Infrastructure;
using mission9_ear69.Models;

namespace mission9_ear69.Pages
{
    public class ShoppingCartModel : PageModel
    {
        private IBookstoreRepository repo { get; set; }
        public Basket basket { get; set; }
        public string ReturnUrl { get; set; }
        public ShoppingCartModel (IBookstoreRepository temp, Basket bas)
        {
            repo = temp;
            basket = bas;
        }
       
        public void OnGet(string returnUrl)

        {
            ReturnUrl = returnUrl ?? "/";


        }
        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            basket.AddItem(b, 1);
      

            return RedirectToPage(new {ReturnUrl = returnUrl });

        }

        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            basket.RemoveItem(basket.Items.First(x => x.Book.BookId == bookId).Book);
            return RedirectToPage(new {ReturnUrl = returnUrl });
        }
    }
}

Pages/Completed.cshtml
@page
@model mission9_ear69.Pages.CompletedModel
@{
}
<div class="text-center">
    <h2>Big thanks.</h2>
    <a class="btn btn-primary" asp-controller="Home">Return to casa</a>
</div>

Pages/ShoppingCart.cshtml
@page
@model mission9_ear69.Pages.ShoppingCartModel
@{
}
<h1>ello mate, dis your shopping cart</h1><span class="label label-success">Success</span>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Book title</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var i in Model.basket.Items)
            {
        <tr>
            <td>@i.Book.Title</td>
            <td>@i.Quantity</td>
            <td>@i.Book.Price</td>
            <td>@(i.Quantity * i.Book.Price)</td>
            <td class="text-center" >
                <form method="post" asp-page-handler="Remove">
                    <input type="hidden" name="bookId" value="@i.Book.BookId" />
                    <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                    <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                </form>
            </td>

        </tr>
            }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.basket.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>
</table>
<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="Checkout" >Checkout</a>
</div>

Pages/_ShoppingCartLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        Book Store
    </div>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>